### ISSUE TITLE
[R] feature request

### ISSUE THREAD

**Issue by mattrix444** [eviqnn/Silky-Spawners#1]
Hey there Eviqnn! Can you please add this, that and maybe a bit of this! and also would it be possible to allow the adjustment of spawner stats please :)

Thanks so much!
From me!

**Comment by 0xEviqnn** [comment]
I will be on this after I have pushed a fix for #2

**Comment by eviqnn** [comment]
Should be featured in 1.3
Meanwhile, i'll close this issue.
